spring:
  jpa:
    hibernate:
      ddl-auto: create
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    database: 0
server:
  port: 8010
debug: true